//! Build-time formatter for the UAX#29 Grapheme_Break property table.
//!
//! Mirrors the `tools/` codegen pattern (island_manifest_gen.zig): it
//! prints a formatted `src/core/anim/grapheme_table.zig` to the path given
//! as argv[1] (or stdout if none). The output is COMMITTED to the repo so
//! package consumers — who receive only `src` per build.zig.zon `.paths`,
//! never `tools/` — build without ever running this generator. `build.zig`
//! exposes it only as the optional, non-default `gen-grapheme-table` step
//! and degrades gracefully when `tools/` is absent.
//!
//! SOURCE OF TRUTH: this tool reads and reformats the COMMITTED
//! `src/core/anim/grapheme_table.zig` via `@import("grapheme_table")`.
//! It does NOT parse Unicode source files (GraphemeBreakProperty.txt,
//! emoji-data.txt, or any other Unicode.org file). The committed table
//! IS the data; this tool only re-emits it in canonical style.
//!
//! To update coverage, edit the `ranges` array in
//! `src/core/anim/grapheme_table.zig` directly, then run this tool to
//! re-canonicalise formatting. The boundary state machine in grapheme.zig
//! is data-driven and needs no change.
//!
//! Usage:
//!   zig build gen-grapheme-table      # reformat the committed file

const std = @import("std");
const Io = std.Io;

// The canonical range data. We import the committed table as the source of
// truth so the generator and the checked-in artifact can never silently
// drift: regenerating reproduces the committed file byte-for-byte (modulo
// the header). When broadening coverage, update grapheme_table.zig's
// `ranges` (the data) and rerun — this tool reformats it deterministically.
const data = @import("grapheme_table");

const header =
    \\//! Generated by tools/grapheme_table_gen.zig — do not edit by hand.
    \\//! Regenerate with: zig build gen-grapheme-table (writes this file).
    \\//!
    \\//! UNICODE VERSION: 15.1.0
    \\//!
    \\//! A compact, binary-searchable range table of the UAX#29
    \\//! Grapheme_Break property (plus Extended_Pictographic) by codepoint.
    \\//! Used by grapheme.zig's extended-grapheme-cluster boundary state
    \\//! machine. Pure data + lookup — no allocator, no OS calls — so it
    \\//! compiles for both native and wasm32-freestanding island builds.
    \\//!
    \\//! Coverage / correctness boundary is documented in this tool
    \\//! (tools/grapheme_table_gen.zig) and the task report. Codepoints not
    \\//! in any range default to grapheme_break = .other (GB999: break).
    \\
    \\/// UAX#29 Grapheme_Break property values, plus Extended_Pictographic.
    \\pub const Prop = enum(u8) {
    \\    other = 0,
    \\    cr,
    \\    lf,
    \\    control,
    \\    extend,
    \\    zwj,
    \\    regional_indicator,
    \\    prepend,
    \\    spacing_mark,
    \\    l,
    \\    v,
    \\    t,
    \\    lv,
    \\    lvt,
    \\    extended_pictographic,
    \\};
    \\
    \\pub const Range = struct {
    \\    lo: u32,
    \\    hi: u32,
    \\    prop: Prop,
    \\};
    \\
    \\/// Sorted by `lo`, non-overlapping. Binary-search in grapheme.zig.
    \\pub const ranges = [_]Range{
    \\
;

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());

    var stdout_buffer: [64 * 1024]u8 = undefined;

    // argv[1] = output path (optional; stdout otherwise).
    if (args.len >= 2) {
        const cwd = std.Io.Dir.cwd();
        var file = try cwd.createFile(io, args[1], .{});
        defer file.close(io);
        var fw = file.writer(io, &stdout_buffer);
        try emit(&fw.interface);
        try fw.interface.flush();
    } else {
        var sw = Io.File.stdout().writer(io, &stdout_buffer);
        try emit(&sw.interface);
        try sw.interface.flush();
    }
}

fn emit(out: *Io.Writer) !void {
    try out.writeAll(header);
    for (data.ranges) |r| {
        try out.print(
            "    .{{ .lo = 0x{X:0>4}, .hi = 0x{X:0>4}, .prop = .{s} }},\n",
            .{ r.lo, r.hi, @tagName(r.prop) },
        );
    }
    try out.writeAll("};\n");
}
