//! Phase 13B — build-time codegen for the island manifest.
//!
//! Walks `app.islands` at comptime and prints a generated
//! `client_manifest.zig` to stdout. `build.zig` captures the output
//! via `addRunArtifact` + `captureStdOut` and writes it into the
//! build's WriteFiles directory so server- and (Phase 13C) per-chunk
//! WASM modules share a single source of truth for island metadata.
//!
//! Empty `app.islands` is fine — the generator still emits a valid
//! manifest with `entries = &.{}`, which keeps the runtime lookup
//! path identical between apps that use islands and apps that don't.

const std = @import("std");
const Io = std.Io;
const app = @import("app");

pub fn main(init: std.process.Init) !void {
    const io = init.io;

    var stdout_buffer: [16 * 1024]u8 = undefined;
    var stdout_writer = Io.File.stdout().writer(io, &stdout_buffer);
    const out = &stdout_writer.interface;

    try out.writeAll(
        \\// Generated by tools/island_manifest_gen.zig — do not edit.
        \\// Lists every island declared under `app.islands`. The runtime
        \\// looks up entries by name when handling `<verve-island>`
        \\// markers; `chunk_url` is the per-island WASM chunk path JS
        \\// fetches on demand.
        \\
        \\pub const Entry = struct {
        \\    name: []const u8,
        \\    props_schema: []const u8,
        \\    chunk_url: []const u8,
        \\};
        \\
        \\pub const entries: []const Entry = &.{
        \\
    );

    if (@hasDecl(app, "islands")) {
        const Islands = app.islands;
        const decls = comptime std.meta.declarations(Islands);

        inline for (decls) |decl| {
            const T = @field(Islands, decl.name);
            const info = @typeInfo(@TypeOf(T));
            // Each island is a struct type (its decls carry per-island
            // metadata like `props_schema`). Skip anything else so the
            // namespace can host helpers alongside actual islands.
            if (info != .type) continue;
            const TypeT = T;
            const tt_info = @typeInfo(TypeT);
            if (tt_info != .@"struct") continue;

            const schema: []const u8 = if (@hasDecl(TypeT, "props_schema"))
                @field(TypeT, "props_schema")
            else
                "{}";

            try out.print("    .{{ .name = \"{s}\", .props_schema = \"", .{decl.name});
            for (schema) |c| switch (c) {
                '"' => try out.writeAll("\\\""),
                '\\' => try out.writeAll("\\\\"),
                '\n' => try out.writeAll("\\n"),
                else => try out.writeByte(c),
            };
            try out.print("\", .chunk_url = \"/islands/{s}.wasm\" }},\n", .{decl.name});
        }
    }

    try out.writeAll(
        \\};
        \\
        \\pub fn lookup(name: []const u8) ?Entry {
        \\    const std_mod = @import("std");
        \\    for (entries) |e| {
        \\        if (std_mod.mem.eql(u8, e.name, name)) return e;
        \\    }
        \\    return null;
        \\}
        \\
    );

    try out.flush();
}
