//! Phase 11 — build-time codegen for typed server-fn client stubs.
//!
//! Walks `app.Actions` at comptime and prints a generated `app_client.zig`
//! to stdout. `build.zig` captures the output via `addRunArtifact` +
//! `captureStdOut` and writes it into the build's WriteFiles directory
//! so both server- and (eventually) wasm-side modules can import a
//! typed call surface alongside the runtime `verveServerFn` escape
//! hatch.

const std = @import("std");
const Io = std.Io;
const app = @import("app");

pub fn main(init: std.process.Init) !void {
    const io = init.io;

    var stdout_buffer: [16 * 1024]u8 = undefined;
    var stdout_writer = Io.File.stdout().writer(io, &stdout_buffer);
    const out = &stdout_writer.interface;

    try out.writeAll(
        \\// Generated by tools/server_fn_codegen.zig — do not edit.
        \\// Walks `app.Actions` at build time and emits a typed wrapper
        \\// for each `pub fn`. Native callers reach the action directly;
        \\// Phase 12 will add a parallel wasm-side dispatch path.
        \\
        \\const std = @import("std");
        \\const app = @import("app");
        \\const verve = @import("verve");
        \\
        \\
    );

    const Actions = app.Actions;
    const decls = comptime std.meta.declarations(Actions);

    inline for (decls) |decl| {
        const value = @field(Actions, decl.name);
        const T = @TypeOf(value);
        if (@typeInfo(T) != .@"fn") continue;
        const fn_info = @typeInfo(T).@"fn";
        if (fn_info.params.len != 1) continue;
        if (fn_info.return_type == null) continue;

        try out.print(
            \\pub fn {[n]s}(
            \\    arena: std.mem.Allocator,
            \\    args: @typeInfo(@TypeOf(app.Actions.{[n]s})).@"fn".params[0].type.?,
            \\) @typeInfo(@TypeOf(app.Actions.{[n]s})).@"fn".return_type.? {{
            \\    return verve.serverFnGen.invoke(app.Actions.{[n]s}, arena, args, "{[n]s}");
            \\}}
            \\
            \\pub fn {[n]s}_post(
            \\    arena: std.mem.Allocator,
            \\    args: @typeInfo(@TypeOf(app.Actions.{[n]s})).@"fn".params[0].type.?,
            \\) void {{
            \\    verve.serverFnGen.post(app.Actions.{[n]s}, arena, args, "{[n]s}");
            \\}}
            \\
            \\
        , .{ .n = decl.name });
    }

    try out.flush();
}
